[package]
edition = "2018"
name = "dexter"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
async-recursion = "0.3.2"
cbz-reader = { path = "../cbz-reader" }
clap = { version = "3.0.7", features = ["derive"] }
cli-table = "0.4.6"
dexter-core = { path = "../dexter-core" }
dialoguer = "0.9.0"
env_logger = "0.9.0"
indicatif = "0.16.2"
log = "0.4.14"
tokio = { version = "1.15.0", features = ["full"] }
