[workspace]
resolver = "2"
members = [
  "dexter-core",
  "dexter",
  "cbz",
  "cbz-dexter-reindex",
  "cbz-merge",
  "cbz-reader",
]

[workspace.package]
rust-version = "1.65"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.68"
async-recursion = "1.0.0"
bytes = "1.3.0"
camino = "1.1.1"
cbz = { path = "./cbz" }
cbz-reader = { path = "./cbz-reader" }
clap = { version = "4.0.32", features = ["derive"] }
cli-table = "0.4.7"
dexter-core = { path = "./dexter-core" }
dialoguer = "0.10.2"
env_logger = "0.9.3"
futures = "0.3.25"
glob = "0.3.1"
iced = "0.4.2"
iced_native = "0.5.1"
indicatif = "0.17.2"
log = "0.4.17"
reqwest = "0.11.13"
reqwest-middleware = "0.2.0"
reqwest-retry = "0.2.1"
sanitize-filename = "0.4.0"
serde = "1.0.152"
thiserror = "1.0.38"
tokio = "1.24.1"
url = "2.3.1"
zip = "0.6.3"
