[package]
name = "cbz-merge"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
glob.workspace = true
sanitize-filename.workspace = true
zip.workspace = true
