[package]
edition = "2018"
name = "dexter-core"
version = "0.1.0"

[dependencies]
anyhow = "1.0.52"
bytes = "1.1.0"
futures = "0.3.19"
log = "0.4.14"
reqwest = { version = "0.11.9", features = ["json"] }
serde = { version = "1.0.133", features = ["derive"] }
tokio = { version = "1.15.0", features = ["full"] }
url = "2.2.2"
zip = "0.5.13"
