[package]
edition = "2018"
name = "dexter-core"
version = "0.1.0"

[dependencies]
anyhow = "1.0.42"
bytes = "1.0.1"
futures = "0.3.16"
log = "0.4.14"
reqwest = {version = "0.11.4", features = ["json"]}
serde = {version = "1.0.126", features = ["derive"]}
tokio = {version = "1", features = ["full"]}
url = "2.2.2"
zip = "0.5.13"
