[package]
name = "cbz"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
bytes.workspace = true
camino.workspace = true
glob.workspace = true
sanitize-filename.workspace = true
thiserror.workspace = true
zip.workspace = true
