[package]
name = "cbz-reindex"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dexter-core.workspace = true
env_logger.workspace = true
tokio = { workspace = true, features = ["full"] }
zip.workspace = true
